Laravel 9 support
fortrabbit/laravel-object-storage pull request #7
Opened 2022-02-09 13:26 UTC by ostark

see https://github.com/fortrabbit/laravel-object-storage/issues/6
--
WIP

2022-02-09 15:51 UTC, alexpestell requested changes
I haven't tested this, and not used it before, but here are a few suggestions.

2022-02-09 15:51 UTC, alexpestell commented on src/ObjectStorageAdapter.php
> +
I guess I would use typed properties here. I'd also put them in the same order they occur in the constructor, but that's probably a bit OCD.

2022-02-09 15:51 UTC, alexpestell commented on README.md
Further down: "available" statt "avaible"

2022-02-09 15:51 UTC, ghost commented on src/ObjectStorageAdapter.php
>  use Aws\S3\Exception\S3Exception;
`use Aws\S3\Exception\S3Exception` can be removed

2022-02-09 15:51 UTC, alexpestell commented on src/ObjectStorageAdapter.php
> +            ] + $this->options['params']);
I think this should be `$options['params']`, otherwise it won't pick up the `ContentType` and `ContentLength` values you set above.

2022-02-09 15:51 UTC, alexpestell commented on src/ServiceProvider.php
> +    protected static array $OBJECT_STORAGE_SECRETS = [];
Can remove docblock

2022-02-09 15:51 UTC, alexpestell commented on src/ServiceProvider.php
> +
Nature abhors a vacuum

2022-02-09 15:51 UTC, ghost commented on src/ServiceProvider.php
> +                $visibility,
Just for consistency with the `ObjectStorageAdapter`, I'd call `$root` `$prefix`, and `$visibility` `$visibilityConverter` 🤷

2022-02-09 16:22 UTC, ostark commented
Valid remarks, thanks @alexpestell

2022-02-10 09:22 UTC, ostark commented on src/ObjectStorageAdapter.php
> +
I'd keep this as the parent class

2022-02-10 09:24 UTC, ostark commented on src/ObjectStorageAdapter.php
> +            ] + $this->options['params']);
Ah, that was the reason why no content-length header wasn't there ;-)

2022-02-11 10:23 UTC, merged